### PR TITLE
Add camel-kamelets-catalog and camel-kamelets-utils to the camel-spring-boot BOM

### PR DESCRIPTION
**Pull request by cunningt**
@oscerd

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The problem is we are going to release camel and csb first. So the released bom won't be aligned. I don't think there is a good solution for this unless we release kamelets after camel and then csb.

**Comment by rinaldodev** [comment]
> The problem is we are going to release camel and csb first. So the released bom won't be aligned. I don't think there is a good solution for this unless we release kamelets after camel and then csb.

camel -> kamelets -> csb does seem like a good approach, but does it affect this PR?

**Comment by oscerd** [comment]
I'm against changing the release order. It is working fine upstream and adding another step is not on the roadmap. Today camel and csb are released together in a unique vote. Adding Kamelets complicates things

**Review by davsclaus — CHANGES_REQUESTED** [review]
same as andrea

**Comment by rinaldodev** [comment]
I see. So if I understood correctly we are not including the catalog as a dependency in neither camel or csb, right?

If true, then I believe we should update these instructions? https://github.com/apache/camel-kamelets/blob/4.8.x/README.md?plain=1#L5

**Comment by oscerd** [comment]
We are including camel kamelets dependency in camel jbang

Il sab 19 ott 2024, 17:31 Rinaldo Pitzer Júnior ***@***.***>
ha scritto:

**Pull request closed without merging**
