### PR TITLE
Fix catalog tests

### PR DESCRIPTION
**Pull request by Croway**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by Croway** [comment]
Hello @oscerd is it possible to have this PR and https://github.com/apache/camel-spring-boot/pull/709 merged before the next Camel-Spring-Boot Daily JDK17 run?

**Comment by davsclaus** [comment]
yeah we can manuallly kick a new job

**Comment by oscerd** [comment]
Done

**Comment by Croway** [comment]
Thanks!, as you prefer, I think that the job will start in 1h.

**Pull request merged**
