### PR TITLE
CAMEL-18932: added missing log4j versions

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@davsclaus do you mind a second look, please? This should fix the build break, but I don't want to interfere w/ other activities for CAMEL-18932.

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
Obs.: failing because the `camel-dependencies` pom in the cache is using version 2.18.0 for log4j, which seems unavailable.

**Comment by davsclaus** [comment]
you should use 2.19.0 version of log4j

**Comment by davsclaus** [comment]
I assume this is working now and we can close this PR ?

**Comment by orpiske** [comment]
> you should use 2.19.0 version of log4j

i am not suing any version here ... it's taking from Camel. Do you mean I should bypass it?

**Comment by orpiske** [comment]
> I assume this is working now and we can close this PR ?

I haven't tried it, but if it's working now, let's close it.

**Pull request closed without merging**
