### PR TITLE
Document update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Changes from "balabncer" to "balancer"

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This is generated from javadoc.. you need to update it there

**Comment by NiteshKoushik** [comment]
Can you please share the javadoc link, tried checking the files. Since there are many files difficult to find the actual file which is pointing to it.

**Comment by NiteshKoushik** [comment]
I have not got any javadoc file, got 2 files, done the changes in both the files
one under
camel-spring-boot-master\camel-spring-boot-master\docs\modules\ROOT\pages
and another under
camel-spring-boot-master\camel-spring-boot-master\core\camel-spring-cloud-netflix\src\main\docs

If it has to be done in javadoc, please share the link as I am not getting the exact document.

**Review by oscerd — APPROVED** [review]
My bad, this stuff is hard-coded

**Pull request merged**
