### PR TITLE
Document update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Grammatical correction

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Those are autogenerated from source code javadoc, you need to modify the javadoc

**Comment by NiteshKoushik** [comment]
How to go to the Javadoc of each file. Is there a way to navigate to its base link.

**Comment by oscerd** [comment]
Grep the phrase

**Comment by oscerd** [comment]
And clone the project locally

**Comment by NiteshKoushik** [comment]
Can you please share the javadoc link, tried checking the files. Since there are many files difficult to find the actual file which is pointing to it.

**Comment by NiteshKoushik** [comment]
Is it possible to share the Javadoc link.

**Comment by oscerd** [comment]
https://github.com/apache/camel-spring-boot/blob/master/core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelConfigurationProperties.java

**Comment by NiteshKoushik** [comment]
Hello @oscerd, Thanks for sharing the javadoc link. I have done the changes in the javadoc link. But the changes are partial, I was not able to do complete changes in the given link, when compare to the changes which are present here. Also I feel partial code is getting generated from Javadoc and other piece of code is getting referred directly.

**Comment by oscerd** [comment]
Thanks, you could split in two different PRs and close this one

**Comment by NiteshKoushik** [comment]
Ok. Thanks

**Pull request closed without merging**
