### PR TITLE
Adding jenkinsfile(jdk11) for ppc64le

### PR DESCRIPTION
**Pull request by sanskruti1098**

### CODE REVIEW

**Comment by davsclaus** [comment]
Camel 4 requires JDK17 or 21.

**Comment by shreyakajbaje** [comment]
> Camel 4 requires JDK17 or 21.

Hi @davsclaus thanks for reply. there is camel jdk 11 job available https://builds.apache.org/job/Camel/job/Apache%20Camel/job/camel-3.21.x/106/ for v3.21.x we have been referring to the same. also currently willing to get jdk11 camel-spring-boot job enabled for Power. cc @sanskruti1098

**Comment by oscerd** [comment]
Camel 4 needs JDK 17 at least

**Comment by sanskruti1098** [comment]
Hi @davsclaus @oscerd we are trying to enable JDK11 jobs for power for camel3.x similar to x86 job

**Comment by oscerd** [comment]
I don't think it should be on main branch then

**Comment by sanskruti1098** [comment]
Hi @oscerd I have tested branch 3.21.x on PowerPC should I go ahead with the same branch?

**Comment by oscerd** [comment]
I'll have a look next week.

**Comment by shreyakajbaje** [comment]
> I'll have a look next week.

 thank you @oscerd please let us know!

**Pull request closed without merging**
