### PR TITLE
Added support for Micrometer Observation

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
fixes https://issues.apache.org/jira/browse/CAMEL-19209

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
Folks, I am not entirely sure if it is related to this, but Camel Spring Boot 3.x is currently failing due to errors on `camel-observation-starter`. I wonder if there's something we need to backport? 

For instance: https://github.com/apache/camel-spring-boot/actions/runs/4642261316

**Comment by marcingrzejszczak** [comment]
```
Error:    symbol:   method toList()
```

Are you using proper JDK in the build?

**Comment by orpiske** [comment]
> ```
> Error:    symbol:   method toList()
> ```
> 
> Are you using proper JDK in the build?

Yes, our build is using the right JDK for Camel Spring Boot 3x: 

```
...
  with:
    distribution: temurin
    java-version: 11
    cache: maven
    java-package: jdk
...
```

**Comment by marcingrzejszczak** [comment]
That's not a good version. Spring Boot 3 requires JDK 17.

**Comment by davsclaus** [comment]
does micrometer observation requires java 17 and spring boot 3 

camel 3.x is java 11 and spring boot 2
camel 4.x is java 17 and spring boot 3

**Comment by orpiske** [comment]
@marcingrzejszczak Please keep in mind I talking about Camel Spring Boot 3.x (CSB), not Spring Boot 3. CSB uses Spring Boot 2 and requires Java 11.

**Comment by marcingrzejszczak** [comment]
So for Camel 3.x I copied over the configuration from Spring Boot 3 which requires JDK17 (e.g. in `OpenTelemetryAutoConfiguration`). There's the `toList()` method being used. It's enough to change these and it should be fine. I'm really surprised that the build didn't catch it earlier.

**Comment by davsclaus** [comment]
Here is a PR to make it compile with Java 11
https://github.com/apache/camel-spring-boot/pull/810

**Pull request merged**
