### PR TITLE
[CAMEL-20675] move cluster service implementations to dedicated starters

### PR DESCRIPTION
**Pull request by lburgazzoli**
- **[CAMEL-20675] move kubernetes cluster service to its own starter**
- **[CAMEL-20675] move file lock cluster service to its own starter**
- **[CAMEL-20675] move jgroups raft cluster service to its own starter**
- **[CAMEL-20675] move jgroups lock cluster service to its own starter**
- **[CAMEL-20675] move zookeeper cluster service to its own starter**
- **[CAMEL-20675] move infinispan remote cluster service to its own starter**
- **[CAMEL-20675] move consul cluster service to its own starter**
- **[CAMEL-20675] regen**

I'll squash the commits before merge

### CODE REVIEW

**Comment by lburgazzoli** [comment]
This is a draft implementation of [CAMEL-20675](https://issues.apache.org/jira/browse/CAMEL-20675), for the code POV, I think it is pretty ready, but I don't know how to deal with the documentation.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Today I think there are not much docs, the only thing is those tables with all the SB starter options. And with this PR those for cluster/cloud is moved out. 

I guess if you add src/main/docs and add adoc for those new starters then they ought to show up in the website, but that is something we can look at after the code changes.

What about Quarkus should its stuff also be moved out, or we dont have this kind for CEQ today.

**Comment by davsclaus** [comment]
How do we keep those json files up to date, if you do a change in the java file, then the json file is updated also ?

**Comment by Croway** [comment]
> This is a draft implementation of [CAMEL-20675](https://issues.apache.org/jira/browse/CAMEL-20675), for the code POV, I think it is pretty ready, but I don't know how to deal with the documentation.

Hi @lburgazzoli regarding documentation, we may mention it in the release notes, wdyt?

**Review by Croway — APPROVED** [review]

**Comment by lburgazzoli** [comment]
> Today I think there are not much docs, the only thing is those tables with all the SB starter options. And with this PR those for cluster/cloud is moved out.
> 

Yeas I was mainly trying to find out how to include such properties somewhere 

> I guess if you add src/main/docs and add adoc for those new starters then they ought to show up in the website, but that is something we can look at after the code changes.
> 

+1

> What about Quarkus should its stuff also be moved out, or we dont have this kind for CEQ today.

For Quarkus I did it already (as today the only have support for kubernetes and file cluster service)

**Comment by lburgazzoli** [comment]
> How do we keep those json files up to date, if you do a change in the java file, then the json file is updated also ?

Yes they are, those json have been auto generated bu some of the maven/camel/sb plugins

**Review by davsclaus — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by lburgazzoli** [comment]
> Need to update the 4.6 upgrade guide doc with this change (in core project)

https://github.com/apache/camel/pull/13830, let me know if you want to expand it more

**Review by Croway — APPROVED** [review]

**Pull request merged**
