### PR TITLE
CAMEL-14672: Invoke customizers as part of services initialization

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Requires https://github.com/apache/camel/pull/4152

**Review by oscerd — CHANGES_REQUESTED** [review]
I think you don't have a full camel 3.5.x aligned as snapshot, these fields are needed

**Comment by lburgazzoli** [comment]
@davsclaus @oscerd there's a huge number of files touched by this PR but most of them are the auto generated one, I still need to add some examples for basic testing to ensure there's no regressions but would be nice to have a review before any further enhancement

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Yeah the regen files will be updated again when you are on latest camel snapshot.

Looks good and the SB auto configurations are now much simpler 

+1

**Comment by lburgazzoli** [comment]
ok, pushed the regen

**Review by oscerd — APPROVED** [review]

**Pull request merged**
