### PR TITLE
CAMEL-18933: Adjust auto configuration to load Spring Boot 3

### PR DESCRIPTION
**Pull request by Croway**
- The following class was changed https://github.com/Croway/camel-spring-boot/blob/14639626a6b2b536b3818698f988076ff3f874e4/tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/SpringBootAutoConfigurationMojo.java
- deletion of spring.factories
- `mvn clean install` in order to generate the `AutoConfiguration.imports` 
- endpoint-dsl related `AutoConfiguration.imports` added manually

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Amazing

**Comment by Croway** [comment]
I had to convert it to draft, there are some AutoConfiguration s classes that are not automatically added, I'll look into it

**Comment by Croway** [comment]
Some AutoConfiguration were not added automatically, I've manually added them [Manually added AutoConfiguration](https://github.com/apache/camel-spring-boot/pull/705/commits/663ac4a77921f356ef34357d2a5627bdb78fbc77), I'll check why on the Mojo.

**Comment by Croway** [comment]
infinispan tests need to be updated, @orpiske did you face the following issue `java.lang.NoClassDefFoundError: Could not initialize class org.infinispan.configuration.cache.TransactionConfiguration` during camel-infinispan test review?

**Comment by orpiske** [comment]
> infinispan tests need to be updated, @orpiske did you face the following issue `java.lang.NoClassDefFoundError: Could not initialize class org.infinispan.configuration.cache.TransactionConfiguration` during camel-infinispan test review?

I don't remember if that's the specific issue I had, but we still have 2 or 3 test issues in Infinispan. That could be it.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
