### PR TITLE
CAMEL-15624 : Fixing complex types issue on spring starters component Configuration

### PR DESCRIPTION
**Pull request by alxpark**
By fixing complex types in camel-spring-boot-generator-maven-plugin, camel spring starters auto configuration type issues will be resolved not only IDE, but also applying them on runtime. 
By this change, some of modules brought another type errors by java.util.Duration.
It's duration type, but Java type was either Long or Integer. 
So, convertDurationToMillesec() introduced to generate the value correctly.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
If you can use the Camel codestyle it would be good. This requires some attention, because it could break existing users.

**Comment by alxpark** [comment]
@oscerd Thank you for your review. I'll revise the style for Camel.

**Comment by oscerd** [comment]
Also, this will break tests for sure.

**Comment by alxpark** [comment]
@oscerd 

> Also, this will break tests for sure.

Yes, so I sent another PR on camel in order to fix this unit test error.
this should be merged in advance. https://github.com/apache/camel/pull/4356

**Comment by alxpark** [comment]
> If you can use the Camel codestyle it would be good. This requires some attention, because it could break existing users.

@oscerd I updated my codes by Camel code style using this : https://github.com/apache/camel/blob/master/etc/eclipse/CamelCodeFormatter.xml
Please let me know if I need to check further. thx

**Comment by alxpark** [comment]
> @oscerd
> 
> > Also, this will break tests for sure.
> 
> Yes, so I sent another PR on camel in order to fix this unit test error.
> this should be merged in advance. [apache/camel#4356](https://github.com/apache/camel/pull/4356)

@oscerd you're right. My codes tested based on 3.5.0 version, not 3.6.0-SNAPSHOT. I thought I all fixed the clashes, but I re-ran the unit tests on 3.6.0 and found 3 more crashes.  Hmm.... I will have a look tomorrow.

**Comment by alxpark** [comment]
> > @oscerd
> > > Also, this will break tests for sure.
> > 
> > 
> > Yes, so I sent another PR on camel in order to fix this unit test error.
> > this should be merged in advance. [apache/camel#4356](https://github.com/apache/camel/pull/4356)
> 
> @oscerd you're right. My codes tested based on 3.5.0 version, not 3.6.0-SNAPSHOT. I thought I all fixed the clashes, but I re-ran the unit tests on 3.6.0 and found 3 more crashes. Hmm.... I will have a look tomorrow.

**All cleared 3 broken modules after I recompiled today.** I assume that it's  camel's 3.6.0-night build tar files 
I saw the root causes of the test errors and source generated by invalid default value(type error) derived from camel modules somewhere., but it's cleared after I compiled based on master branch.  So, my code changes will be ok..

I think **only "camel-wordpress-starter" test will be broken by this PR until the other PR for "camel-wordpress" merged into camel repo.**  as conflict WordpressComponentConfigration class in both.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Merged this manually thanks.

Can you test with latest code, and make sure it works with the spring STS tooling, for example for types that has generics such as a java.util.Map<x, y> - not sure how the tooling understands that.

**Comment by alxpark** [comment]
> Merged this manually thanks.
> 
> Can you test with latest code, and make sure it works with the spring STS tooling, for example for types that has generics such as a java.util.Map<x, y> - not sure how the tooling understands that.

Thanks @davsclaus for the merging this, hopefully it corrects a lot of complex type properties in camel spring boot starters. 
I verified my original undertow-starter httpOptions issue and it resolved not only autoconfig in tool, but also actually recognised the options in runtime. 
I will test Map<> type config in STS and will come back. need to find one as a sample.

**Comment by alxpark** [comment]
> > Merged this manually thanks.
> > Can you test with latest code, and make sure it works with the spring STS tooling, for example for types that has generics such as a java.util.Map<x, y> - not sure how the tooling understands that.
> 
> Thanks @davsclaus for the merging this, hopefully it corrects a lot of complex type properties in camel spring boot starters.
> I verified my original undertow-starter httpOptions issue and it resolved not only autoconfig in tool, but also actually recognised the options in runtime.
> I will test Map<> type config in STS and will come back. need to find one as a sample.

@oscerd  I can confirm that Map<String, Object> type options are working fine in the latest codes as well.
For example, in camel-netty-http-starter, camel.component.netty-http.options is Map<String, Object> type. Tool provides flexible validation, doesn't complain any key and values on this option.
`camel.component.netty-http.options.key1=value1`

**Pull request closed without merging**
