### PR TITLE
CAMEL-14832: Data format for SWIFT financial message conversion support

### PR DESCRIPTION
**Pull request by essobedo**
Related to https://issues.apache.org/jira/browse/CAMEL-14832

## Motivation

A new swift component has been added to Camel and should be proposed in Camel-Spring-Boot.

## Modifications:

* Add a new starter called `camel-swift-starter`

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
For SB then sometimes the doc files need to have a special header for the website build to work.

Try comparing
https://raw.githubusercontent.com/apache/camel/main/components/camel-swift/src/main/docs/swiftMt-dataformat.adoc

With an old
https://raw.githubusercontent.com/apache/camel/main/components/camel-any23/src/main/docs/any23-dataformat.adoc

**Review by oscerd — APPROVED** [review]

**Comment by essobedo** [comment]
> For SB then sometimes the doc files need to have a special header for the website build to work.
> 
> Try comparing https://raw.githubusercontent.com/apache/camel/main/components/camel-swift/src/main/docs/swiftMt-dataformat.adoc
> 
> With an old https://raw.githubusercontent.com/apache/camel/main/components/camel-any23/src/main/docs/any23-dataformat.adoc

Are you referring to the `camel-spring-boot-name`?

**Comment by davsclaus** [comment]
yes

**Comment by essobedo** [comment]
Yeah, I'm aware of it, I just wait to add it to SB repo before adding it to the Camel doc pages

**Comment by essobedo** [comment]
Here is the corresponding PR https://github.com/apache/camel/pull/8638

**Pull request merged**
