### PR TITLE
Micrometer observation

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
Spring Boot configuration for 

- Camel MicrometerObservation tracer
- Micrometer Observation
- Micrometer Tracing

Micrometer Observation and Micrometer Tracing configuration will be removed for Spring Boot 3.x.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
Spring Boot example https://github.com/apache/camel-spring-boot-examples/pull/98

**Comment by davsclaus** [comment]
Remove `@author` tags from javadoc, and the license files in top of the source file should be 100% identical to what we use in the other starters. The ones in this PR are a little bit different.

**Comment by marcingrzejszczak** [comment]
> Remove @author tags from javadoc, and the license files in top of the source file should be 100% identical to what we use in the other starters. The ones in this PR are a little bit different.

Yeah, cause I copied this from Spring Boot code. How do we approach this problem? Will a note in the `package-info` be enough to show that this whole package was taken from a different location?

**Comment by davsclaus** [comment]
yeah you can do that

**Review by davsclaus — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
Prerequisite - https://github.com/apache/camel/pull/9583

**Comment by davsclaus** [comment]
We also need PR for main branch

**Comment by marcingrzejszczak** [comment]
https://github.com/apache/camel-spring-boot/pull/802

**Pull request merged**
