### PR TITLE
Added Spring Boot XML DSL archetype

### PR DESCRIPTION
**Pull request by fg78nc**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by fg78nc** [comment]
HI,

According to documentation Camel will pick up XML context/route definition
from the classpath.
However it did not work, unless I explicitly add @ImportResource.
It did not even work after adding camel.springboot.xml-routes to
application.properties.
Is it expected behavior?

**Comment by oscerd** [comment]
This is a good question, we did some change after 3.4.x LTS. @davsclaus can you shed some light on XML routes in SB?

**Comment by davsclaus** [comment]
Its 2 different thing

spring xml files with <beans> are ONLY spring that can load this via that spring boot @import resource annotation.

The xml routes is ONLY for Camel XML files which are <routes> xml snippets (not spring at all).

**Comment by fg78nc** [comment]
Oh, I see now.
I will try that. Where can I see an example of XML structure of Camel xml
route?
Is it just a route definition, similar to what can be dropped into ActiveMQ?
Also probably documentation has to be updated in several places, including
https://camel.apache.org/manual/latest/xml-configuration.html and
https://camel.apache.org/components/latest/spring-summary.html ?

**Comment by davsclaus** [comment]
The old world with spring xml files (eg beans) is not something for spring boot. So we are not looking for a maven archetype that does this.

**Comment by fg78nc** [comment]
I agree with you, it is not an idiomatic way for modern Spring Boot
development.
However please consider use cases where a user wants to migrate their Camel
application running on Fuse/Karaf to Spring Boot Java DSL.

**Comment by fg78nc** [comment]
@davsclaus @oscerd Please review and make a decision.

**Comment by oscerd** [comment]
I think we should close this without merging.

**Comment by oscerd** [comment]
Thanks anyway.

**Pull request closed without merging**
